### ISSUE TITLE
RosException - https://github.com/aluisiora/routeros-client/issues/8

### ISSUE THREAD

**Issue by ramwolken9** [aluisiora/node-routeros#16]
Hi,

[I'm using routeros-client](https://github.com/aluisiora/routeros-client)

#[Ref issue](https://github.com/aluisiora/routeros-client/issues/8)

Could you please look into this @aluisiora 

Error: RosException: Timed out after 10 seconds
at RosException (..../node_modules/node-routeros/dist/RosException.js:11:14)
at onTimeout (..../node_modules/node-routeros/dist/connector/Connector.js:180:33)
at onceWrapper (events.js:277:12)
at emit (events.js:189:12)
at EventEmitter.emit (domain.js:459:22)
at Socket._onTimeout (net.js:440:7)
at ontimeout (timers.js:436:10)
at tryOnTimeout (timers.js:300:4)
at listOnTimeout (timers.js:263:4)
at processTimers (timers.js:223:9)

**Comment by aluisiora** [comment]
I'll look into it, nothing was changed for a long time with the source code so it could be that new versions of RouterOS had changes.

What version of RouterOS were you using?

**Comment by ramwolken9** [comment]
Hey @aluisiora , Thanks for that, 
I'm testing using 6.44.3 (stable) version.
I observed it is happening when the device go offline without proper disconnection / Sudden poweroff of the device, something like that .

> Shall we keep track on this issue here and close the other duplicate [on routeros-client](https://github.com/aluisiora/routeros-client/issues/8) / vice versa

**Comment by ZackMattor** [comment]
I would think this behavior is expected when the device goes offline?  I would think the socket should throw an error before the timeout though? I've noticed similar stuff when just ripping an ethernet jack from my computer during testing. It hits the timeout.

**Comment by aluisiora** [comment]
Couldn't test it yet, but it should be the expected behavior. If you could connect at least once, you have to listen to the 'error' event if the connection eventually fails and then treat it.

[Wiki reference](https://github.com/aluisiora/node-routeros/wiki/Connecting,-disconnecting,-reconnecting#error-event-after-connected)

If you try to connect the first time and it fails, the promise will be rejected and you can catch it with a try-catch, but the way I found after you have connected and then later the connection was lost, was triggering the 'error' event informed that a timeout was reached.

Let me know if that fixes it for you.

**Comment by ramwolken9** [comment]
@aluisiora  It worked, Thank you!
